[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
libs = ["lib"]
extra_output = ["storageLayout"]
solc = "0.8.28"
evm_version = "cancun"
ignored_error_codes = [
    3420, # pragma-solidity
    1878, # SPX
    5574, # Disable the specific warning code for contract size in tests
    3860, # Disable the specific warning code 3860 in tests
    2394, # Transient storage warning
    5667, # Unuesed parameter
    2072, # Unuesed local variable
]

# optimizer = true
# optimizer-runs = 1_000_000
# dynamic_test_linking=true
fs_permissions = [{ access = "read-write", path = "./" }]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
auto_detect_remappings = false
remappings = [
    "@contracts/=./contracts/",
    "@tests/=./tests/",
    "@openzeppelin/=lib/openzeppelin-contracts",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable",
    "@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "@safe/=lib/safe-smart-account/contracts/",
]

[rpc_endpoints]
forkito = 'http://127.0.0.1:8545'
mainnet = '${FORK_RPC}'
staging = 'https://rpc.tangent.finance'

base = 'https://base.llamarpc.com'

[fuzz]
runs = 10
depth = 10
# fuzz_runs = 10

[invariant]
runs = 10
depth = 10
dictionary_weight = 80
preserve_state = true
# fail_on_revert = true
shrink_run_limit = 3
fuzz_runs = 5
