[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
libs = ["lib"]
extra_output = ["storageLayout"]

ignored_error_codes = [
    3420, # pragma-solidity
    1878, # SPX
]

fs_permissions = [
    { access = "read-write", path = "./" }
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
solc = "0.8.25"
evm_version = "cancun"
[rpc_endpoints]
mainnet = 'https://eth-mainnet.g.alchemy.com/v2/hDva-MsYmcDn3GhDTeMYHq4iKLiT1NYy'