interface ICvgCVX {
    function CRV() external view returns (address);
    function CVG() external view returns (address);
    function CVX() external view returns (address);
    function CVX_CRV_REWARDS() external view returns (address);
    function CVX_LOCKER() external view returns (address);
    function FXS() external view returns (address);
    function acceptOwnership() external;
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function burn(uint256 amount) external;
    function capCVXRushForIndex(uint256) external view returns (uint128 cap, uint128 ratio);
    function capCvgCvx() external view returns (uint256);
    function clearDelegate(bytes32 id) external;
    function convertCvgCVXToCVX(address receiver, uint256 cvgCvxAmount, uint256 minCvxAmount) external;
    function convertCvxToCvgCVXWithSwap(address receiver, uint256 cvxAmountIn, uint256 minCvgCvxAmountOut) external;
    function cvgControlTower() external view returns (address);
    function cvgCvxAlreadyMintedWithRush() external view returns (uint256);
    function cvgRewards() external view returns (address);
    function cvx1() external view returns (address);
    function cvxDelegateRegistry() external view returns (address);
    function cvxRewardDistributor() external view returns (address);
    function cvxStakingPositionService() external view returns (address);
    function cvxToLock() external view returns (uint256);
    function decimals() external view returns (uint8);
    function decreaseAllowance(address spender, uint256 subtractedValue) external returns (bool);
    function delegate(bytes32 id, address account) external;
    function getCvxRushAmounts(uint256 amountCvx, bool isLock) external view returns (uint256, uint256);
    function increaseAllowance(address spender, uint256 addedValue) external returns (bool);
    function isSpecialMinter(address) external view returns (bool);
    function lockCvx() external;
    function lockingPositionService() external view returns (address);
    function mint(address to, uint256 amount, bool isLock) external returns (uint256);
    function mintCVXRush(uint256 tokenId, uint128 cvxAmount, address to, address cvgLockReceiver, bool isLock) external returns (uint256);
    function mintFees() external view returns (uint256);
    function mintFrom(address from, address to, uint256 amount, bool isLock) external returns (uint256);
    function owner() external view returns (address);
    function pendingOwner() external view returns (address);
    function poolCvgCvxCvx1() external view returns (address);
    function renounceOwnership() external;
    function rewardTokensConfigs(uint256) external view returns (address token, uint48 processorFees, uint48 convexTreasury);
    function setCapCvgCvx(uint256 _capCvgCvx) external;
    function setCvxDelegateRegistry(address delegateRegistry) external;
    function setCvxRewardDistributor(address _cvxRewardDistributor) external;
    function setCvxStakingPositionService(address _cvxStakingPositionService) external;
    function setMintFees(uint256 _fees) external;
    function setPoolCvgCvxCvx1AndApprove(address _poolCvgCvxCvx1) external;
    function toggleIsSpecialMinter(address specialMinter) external;
    function totalSupply() external view returns (uint256);
    function transfer(address to, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transferOwnership(address newOwner) external;
    function withdrawCvxCrv(uint256 amount, bool claim) external;
    function withdrawableFees(address) external view returns (uint256);
}
