interface ICVX1 {
    function CVX() external view returns (address);
    function CVX_CRV() external view returns (address);
    function acceptOwnership() external;
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function convertCVX1ToCvgCVXWithMint(address to, uint256 amount, bool isLock) external;
    function cvgCVX() external view returns (address);
    function cvgControlTower() external view returns (address);
    function cvxRewardPool() external view returns (address);
    function decimals() external view returns (uint8);
    function decreaseAllowance(address spender, uint256 subtractedValue) external returns (bool);
    function getReward() external;
    function increaseAllowance(address spender, uint256 addedValue) external returns (bool);
    function isSpecialMinter(address) external view returns (bool);
    function mint(address to, uint256 amount) external;
    function mintFrom(address from, address to, uint256 amount) external;
    function owner() external view returns (address);
    function pendingOwner() external view returns (address);
    function renounceOwnership() external;
    function setCvgCvx(address _cvgCVX) external;
    function setCvxRewardPool(address _cvxRewardPool) external;
    function stake() external;
    function toggleIsSpecialMinter(address specialMinter) external;
    function totalSupply() external view returns (uint256);
    function transfer(address to, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transferOwnership(address newOwner) external;
    function withdraw(uint256 amount, address to) external;
    function withdrawFrom(uint256 amount, address from, address to) external;
}
