import {commonERC20, convexCrv, convexFxn} from "defi-resources";
import {parseEther} from "ethers";

export const STATIC_CONFIG_CONVEX_CURVE = {
    // STABLES
    crvUSD_USDC: {
        collatName: "crvUSD_USDC",
        collatToken: convexCrv.CRVUSD_USDC.lpToken,
        liquidationThreshold: 94_000,
        maxLTV: 90_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.CRVUSD_USDC.cvxRewardToken,
        pid: convexCrv.CRVUSD_USDC.pid,
    },
    crvUSD_USDT: {
        collatName: "crvUSD_USDT",
        collatToken: convexCrv.CRVUSD_USDT.lpToken,
        liquidationThreshold: 94_000,
        maxLTV: 90_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.CRVUSD_USDT.cvxRewardToken,
        pid: convexCrv.CRVUSD_USDT.pid,
    },
    USDC_USDT: {
        collatName: "USDC_USDT",
        collatToken: convexCrv.USDC_USDT_STRATEGICR.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.USDC_USDT_STRATEGICR.cvxRewardToken,
        pid: convexCrv.USDC_USDT_STRATEGICR.pid,
    },
    frxUSD_USDe: {
        collatName: "frxUSD_USDe",
        collatToken: convexCrv.frxUSD_USDe.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.frxUSD_USDe.cvxRewardToken,
        pid: convexCrv.frxUSD_USDe.pid,
    },
    // ETH STABLE
    frxETH_WETH: {
        collatName: "frxETH_WETH",
        collatToken: convexCrv.frxETH_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.frxETH_WETH.cvxRewardToken,
        pid: convexCrv.frxETH_WETH.pid,
    },
    pxETH_WETH: {
        collatName: "pxETH_WETH",
        collatToken: convexCrv.pxETH_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.pxETH_WETH.cvxRewardToken,
        pid: convexCrv.pxETH_WETH.pid,
    },

    pxETH_stETH: {
        collatName: "pxETH_stETH",
        collatToken: convexCrv.pxETH_stETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.pxETH_stETH.cvxRewardToken,
        pid: convexCrv.pxETH_stETH.pid,
    },

    cbBTC_WBTC: {
        collatName: "cbBTC_WBTC",
        collatToken: convexCrv.cbBTC_WBTC.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.cbBTC_WBTC.cvxRewardToken,
        pid: convexCrv.cbBTC_WBTC.pid,
    },
    // TRI CRYPTO
    USDT_WBTC_WETH: {
        collatName: "USDT_WBTC_WETH",
        collatToken: convexCrv.USDT_WBTC_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.USDT_WBTC_WETH.cvxRewardToken,
        pid: convexCrv.USDT_WBTC_WETH.pid,
    },
    USDC_WBTC_WETH: {
        collatName: "USDC_WBTC_WETH",
        collatToken: convexCrv.USDC_WBTC_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.USDC_WBTC_WETH.cvxRewardToken,
        pid: convexCrv.USDC_WBTC_WETH.pid,
    },
    crvUSD_ETH_CRV: {
        collatName: "crvUSD_ETH_CRV",
        collatToken: convexCrv.crvUSD_ETH_CRV.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.crvUSD_ETH_CRV.cvxRewardToken,
        pid: convexCrv.crvUSD_ETH_CRV.pid,
    },
    GHO_cbBTC_WETH: {
        collatName: "GHO_cbBTC_WETH",
        collatToken: convexCrv.GHO_cbBTC_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.GHO_cbBTC_WETH.cvxRewardToken,
        pid: convexCrv.GHO_cbBTC_WETH.pid,
    },

    // DUO CRYPTO

    CVX_ETH: {
        collatName: "CVX_ETH",
        collatToken: convexCrv.CVX_ETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.CVX_ETH.cvxRewardToken,
        pid: convexCrv.CVX_ETH.pid,
    },
    USR_RLP: {
        collatName: "USR_RLP",
        collatToken: convexCrv.USR_RLP.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.CRV, commonERC20.CVX],
        cvxRewardToken: convexCrv.USR_RLP.cvxRewardToken,
        pid: convexCrv.USR_RLP.pid,
    },
};
export const STATIC_CONFIG_CONVEX_FXN = {
    USDC_fxUSD: {
        collatName: "USDC_fxUSD",
        collatToken: convexFxn.USDC_fxUSD.lpToken,
        liquidationThreshold: 94_000,
        maxLTV: 90_000,
        maxMarketDebt: parseEther("1000000"),
        minimumLoan: parseEther("3000"),
        rewards: [commonERC20.FXN, commonERC20.CRV, commonERC20.CVX],
        pid: convexFxn.USDC_fxUSD.pid,
    },
};
