import { COMMON_ERC20S, ConvexCrvPools } from "@tangent/defi-resources";
import { parseEther } from "ethers";
import { MINIMUM_LOAN } from "../market";

export const STATIC_CONFIG_CONVEX_CURVE = {
    // STABLES
    crvUSD_USDC: {
        collatName: "crvUSD/USDC",
        collatToken: ConvexCrvPools.USDC_crvUSD.lpToken,
        liquidationThreshold: 91_500,
        maxLTV: 91_400,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.USDC_crvUSD.pid,

    },
    crvUSD_USDT: {
        collatName: "crvUSD/USDT",
        collatToken: ConvexCrvPools.USDT_crvUSD.lpToken,
        liquidationThreshold: 94_000,
        maxLTV: 93_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.USDT_crvUSD.pid,
    },
    USDC_USDT: {
        collatName: "USDC/USDT",
        collatToken: ConvexCrvPools.USDC_USDT_STRATEGICR.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 92_500,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.USDC_USDT_STRATEGICR.pid,
    },
    frxUSD_USDe: {
        collatName: "frxUSD/USDe",
        collatToken: ConvexCrvPools.frxUSD_USDe.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 92_500,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.frxUSD_USDe.pid,
    },
    // ETH STABLE
    frxETH_WETH: {
        collatName: "frxETH/WETH",
        collatToken: ConvexCrvPools.WETH_frxETH.lpToken,
        liquidationThreshold: 85_000,
        maxLTV: 84_900,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.WETH_frxETH.pid,
    },
    pxETH_WETH: {
        collatName: "pxETH/WETH",
        collatToken: ConvexCrvPools.WETH_pxETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 92_500,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.WETH_pxETH.pid,
    },

    pxETH_stETH: {
        collatName: "pxETH/stETH",
        collatToken: ConvexCrvPools.pxETH_stETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.pxETH_stETH.pid,
    },

    cbBTC_WBTC: {
        collatName: "cbBTC/WBTC",
        collatToken: ConvexCrvPools.cbBTC_WBTC.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.cbBTC_WBTC.pid,
    },
    // TRI CRYPTO
    USDT_WBTC_WETH: {
        collatName: "USDT/WBTC/WETH",
        collatToken: ConvexCrvPools.USDT_WBTC_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.USDT_WBTC_WETH.pid,
    },
    USDC_WBTC_WETH: {
        collatName: "USDC/WBTC/WETH",
        collatToken: ConvexCrvPools.USDC_WBTC_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.USDC_WBTC_WETH.pid,
    },
    crvUSD_ETH_CRV: {
        collatName: "crvUSD/ETH/CRV",
        collatToken: ConvexCrvPools.crvUSD_ETH_CRV.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.crvUSD_ETH_CRV.pid,
    },
    GHO_cbBTC_WETH: {
        collatName: "GHO/cbBTC/WETH",
        collatToken: ConvexCrvPools.GHO_cbBTC_WETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.GHO_cbBTC_WETH.pid,
    },

    // DUO CRYPTO

    CVX_ETH: {
        collatName: "CVX_ETH",
        collatToken: ConvexCrvPools.CVX_ETH.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.CVX_ETH.pid,
    },
    USR_RLP: {
        collatName: "USR_RLP",
        collatToken: ConvexCrvPools.USR_RLP.lpToken,
        liquidationThreshold: 93_000,
        maxLTV: 85_000,
        maxMarketDebt: parseEther("2000000"),
        minimumLoan: MINIMUM_LOAN,
        rewardTokens: [COMMON_ERC20S.CRV, COMMON_ERC20S.CVX],
        pid: ConvexCrvPools.USR_RLP.pid,
    },
};